### ISSUE TITLE
Set certain encode for response

### ISSUE THREAD

**Issue by dannypsnl** [jackfirth/racket-request#29]
Current code use `port->string` to get string directly, but sometimes the user needs to handle different encodes. I would expect a string can pass to `reencode-input-port` as a keyword argument, and apply `reencode-input-port` if this string existed.

**Comment by jackfirth** [comment]
I haven't used this package in years, and I'm not sure I would today honestly. But if you're interested in a PR for this feature I'd happily merge it.
